// MIT License
//
// Copyright (c) 2019 Agenium Scale
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef NS2_HPP
#define NS2_HPP

// Use this file to use ns2.

// ----------------------------------------------------------------------------
// This a MISC section that contains stuff that I do not know where to put
// or that do not deserve a header of their own.

enum text_align_t { Left, Center, Right };

// ----------------------------------------------------------------------------

/*

Generated by:

for i in `ls -1 *.hpp`; do \
  echo "#include <ns2/`basename ${i}`>"; \
done

*/

#include <ns2/backtrace.hpp>
#include <ns2/config.hpp>
#include <ns2/exception.hpp>
#include <ns2/fs.hpp>
#include <ns2/html.hpp>
#include <ns2/json.hpp>
#include <ns2/levenshtein.hpp>
#include <ns2/loc.hpp>
#include <ns2/markdown.hpp>
#include <ns2/process.hpp>
#include <ns2/string.hpp>
#include <ns2/time.hpp>

// ----------------------------------------------------------------------------

#endif
